services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch

    environment:
      discovery.type: single-node

      xpack.security.enabled: "true"
      xpack.security.authc.api_key.enabled: "true"

      # Local development için TLS şimdilik kapalı.
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"

      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20


  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic-setup

    depends_on:
      elasticsearch:
        condition: service_healthy

    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}

    command:
      - bash
      - -c
      - |
        echo "Configuring kibana_system password..."

        until curl -s \
          -X POST \
          -u "elastic:${ELASTIC_PASSWORD}" \
          -H "Content-Type: application/json" \
          "http://elasticsearch:9200/_security/user/kibana_system/_password" \
          -d "{\"password\":\"${KIBANA_PASSWORD}\"}" \
          | grep -q "^{}"
        do
          echo "Waiting to configure kibana_system..."
          sleep 2
        done

        echo "kibana_system password configured."


  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana

    environment:
      SERVER_HOST: "0.0.0.0"

      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}

      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
      XPACK_SECURITY_ENCRYPTIONKEY: ${KIBANA_SECURITY_KEY}
      XPACK_REPORTING_ENCRYPTIONKEY: ${KIBANA_REPORTING_KEY}

    ports:
      - "5601:5601"

    depends_on:
      setup:
        condition: service_completed_successfully


  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION}
    container_name: apm-server

    command:
      - apm-server
      - -e

      - -E
      - apm-server.host=0.0.0.0:8200

      - -E
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]

      - -E
      - output.elasticsearch.username=elastic

      - -E
      - output.elasticsearch.password=${ELASTIC_PASSWORD}

    ports:
      - "8200:8200"

    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  elasticsearch-data: