// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayBridge.Modules.Merchants.Infrastructure.Persistence;

#nullable disable

namespace PayBridge.Modules.Merchants.Infrastructure.Migrations
{
    [DbContext(typeof(MerchantsDbContext))]
    [Migration("20260708202021_AddMerchantDomainTables")]
    partial class AddMerchantDomainTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("MccId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("MccId");

                    b.HasIndex("MerchantCode")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.HasIndex("Status");

                    b.ToTable("Merchants", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantCategoryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsRestricted");

                    b.ToTable("MerchantCategoryCodes", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantPaymentChannelSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowRefund")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowVoid")
                        .HasColumnType("bit");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DailyAmountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnabledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxAmount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MinAmount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Require3DS")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("MerchantId", "Channel")
                        .IsUnique();

                    b.ToTable("MerchantPaymentChannelSettings", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AllowECommerce")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPhysicalPos")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowRefund")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Priority");

                    b.HasIndex("ProviderCode");

                    b.HasIndex("MerchantId", "ProviderCode")
                        .IsUnique();

                    b.ToTable("MerchantProviderAccounts", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedCredentialPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedKeyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantProviderAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RotatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MerchantProviderAccountId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("MerchantProviderCredentials", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantSector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("MerchantSectors", "merchants");
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.Merchant", b =>
                {
                    b.HasOne("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantCategoryCode", null)
                        .WithMany()
                        .HasForeignKey("MccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantSector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantPaymentChannelSetting", b =>
                {
                    b.HasOne("PayBridge.Modules.Merchants.Domain.Merchants.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantProviderAccount", b =>
                {
                    b.HasOne("PayBridge.Modules.Merchants.Domain.Merchants.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantProviderCredential", b =>
                {
                    b.HasOne("PayBridge.Modules.Merchants.Domain.Merchants.Entities.MerchantProviderAccount", null)
                        .WithMany()
                        .HasForeignKey("MerchantProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
