<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayBridge.BuildingBlocks.Exceptions\PayBridge.BuildingBlocks.Exceptions.csproj" />
  </ItemGroup>

</Project>
